import Head from 'next/head'
import Button from '../components/button/button'
import styles from '../styles/Home.module.scss'
import Link from 'next/link';
import { useRouter } from 'next/router';
import Layout from '../components/layouts/layout';
import { PayWith } from 'components/utils/pay-with/payWith';

export default function Index(props) {  
  const router = useRouter();

  let clickHandler = (e) => {    
    router.push("/collections");
  }
  
  return ( 
    <>
      <Head>
        <title>Online Shopping for Men | TipTop</title>
        <meta name="description" content="Generated by create next app" />      
      </Head>

      <div className={styles.container}>      
        <main className={styles.main}>
          <h1 className={styles.title}>Wear better, look better.</h1>
          <div className='mt-4 font-s-24'>
            Don&apos;t you just love being in apparel?
          </div>

          <Link href="/collections">
            <a>
              <Button className="mt-4 font-s-20" color="primary">
                Let&apos;s go shopping
              </Button>
            </a>
          </Link>    
          
          <PayWith />  
        </main>
      </div>
    </>     
  )
}

Index.getLayout = function(page) {
  return (
    <>
      <Layout marginTop={0} setMarginTop={false}>
        {page}
      </Layout>      
    </>
  );
}
