import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/button/button'
import styles from '../styles/Home.module.scss'
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function Home() {  
  const router = useRouter();

  let clickHandler = (e) => {    
    router.push("/collections");
  }
  
  return ( 
    <>
      <Head>
        <title>Online Shopping for Men | TipTop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <div className={styles.container}>      
        <main className={styles.main}>
          <h1 className={styles.title}>Wear better, look better.</h1>
          <div className='mt-4 font-s-24' onClick={clickHandler}>
            Don&apos;t you just love being in apparel?
          </div>

          <Link href="/collections">
            <a>
              <Button className="mt-4" color="primary">
                Shop now
              </Button>
            </a>
          </Link>        
        </main>

      </div>
    </>     
  )
}
